### ISSUE TITLE
Unexpected ||

### ISSUE THREAD

**Issue by jcgoette** [sql-formatter-org/sql-formatter#433]
**Describe the bug**
`SELECT DUAL.DUMMY || DUAL.DUMMY FROM DUAL` causes web formatter to raise error.

**Expected behavior**

Format per usual:
```
SELECT
  DUAL.DUMMY || DUAL.DUMMY
FROM
  DUAL
```

**Actual behavior**
An Unexpected Error Occurred

Parse error: Unexpected "|| DUAL.DUMMY FROM DUAL"

Please report this at [Github issues page.](https://github.com/sql-formatter-org/sql-formatter/issues)

Stack Trace:

Error: Parse error: Unexpected "|| DUAL.DUMMY
FROM
  DUAL"
    at E.value (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:53856)
    at E.value (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:57875)
    at E.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:26761)
    at E.value (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:11946)
    at T.e.feed (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:4085)
    at Object.parse (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:27486)
    at O.value (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:46992)
    at O.value (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:46861)
    at Module.He (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:256897)
    at HTMLTextAreaElement.format (https://sql-formatter-org.github.io/sql-formatter/index.js:48:31)

**Usage**

- How are you calling / using the library?
  - Web
- What SQL language(s) does this apply to?
  - All as far as I can tell
- Which SQL Formatter version are you using?
  - Web

**Comment by nene** [comment]
Looks like this only fails with `language: 'sql'`. When you select any other dialect from the Language dropdown, the formatter doesn't crash. Transact-SQL also doesn't support it, but it won't crash as it detects `||` as two `|` operators.

Interesting that this hasn't been reported earlier as the `||` operator is even part of Standard SQL. But somehow we've failed to include it to operators list for the default formatter.

Will fix.

**Comment by nene** [comment]
Fixed in 10.5.1
