### ISSUE TITLE
Nested CASE statements crash the parser

### ISSUE THREAD

**Issue by JohniMichels** [sql-formatter-org/sql-formatter#497]
**Describe the bug**
When a query has a nested CASE clause, it crashes the parser.

**Steps to reproduce**
Using a sql file with

```sql
SELECT
    CASE 
        WHEN 1=1 THEN
            CASE WHEN 2=1 THEN 0
            END
    END
```
It runs normally on any query engine.
But when I try to run sql-formatter, it throws a giant error ending with:
```
    at I.T.I.feed (/usr/local/lib/node_modules/sql-formatter/dist/sql-formatter.min.cjs:1:4767)
    at Object.parse (/usr/local/lib/node_modules/sql-formatter/dist/sql-formatter.min.cjs:1:36803)
    at trino.parse (/usr/local/lib/node_modules/sql-formatter/dist/sql-formatter.min.cjs:1:36967)
    at trino.format (/usr/local/lib/node_modules/sql-formatter/dist/sql-formatter.min.cjs:1:36519)
    at xR (/usr/local/lib/node_modules/sql-formatter/dist/sql-formatter.min.cjs:1:224990)
    at new PrettierSQLArgs (/usr/local/lib/node_modules/sql-formatter/bin/sql-formatter-cli.cjs:18:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/sql-formatter/bin/sql-formatter-cli.cjs:117:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  offset: 7,
  token: {
    type: 'CASE',
    raw: 'CASE',
    text: 'CASE',
    start: 51,
    precedingWhitespace: '\n            '
  }
}
```

**Expected behavior**
What did you expect to happen?
Formatting the sql normally.

**Actual behavior**
What happened instead?
Parser throws error

**Usage**

- How are you calling / using the library? using cli and config file
- What SQL language(s) does this apply to? any
- Which SQL Formatter version are you using? 11.0.1

**Comment by nene** [comment]
Thanks for reporting. This should be already fixed in `master`.

I've released 11.0.0-beta.1. You can try it out at let me know if this fixes the problem.
