### ISSUE TITLE
Parse error when 

### ISSUE THREAD

**Issue by tim-watcha** [sql-formatter-org/sql-formatter#524]
**Describe the bug**
try formatting following bigquery sql makes error
`SELECT *
FROM a
WHERE d BETWEEN DATE_TRUNC(PARSE_DATE("%Y%m%d", d1), MONTH) AND PARSE_DATE("%Y", d2)
`

**Expected behavior**
print formatted sql

**Actual behavior**

```[error] hello.sql: Error: Parse error at token: ( at line 3 column 27
[error] Unexpected OPEN_PAREN token: {"type":"OPEN_PAREN","raw":"(","text":"(","start":42}. Instead, I was expecting to see one of the following:
[error]
[error] A AND token based on:
[error]     between_predicate → %BETWEEN _ simple_expression _ ● %AND _ simple_expression
[error]     expression$subexpression$1 →  ● between_predicate
[error]     expression →  ● expression$subexpression$1
[error]     other_clause$ebnf$1 → other_clause$ebnf$1 ● expression
[error]     other_clause → %RESERVED_COMMAND ● other_clause$ebnf$1
[error]     clause$subexpression$1 →  ● other_clause
[error]     clause →  ● clause$subexpression$1
[error]     expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause
[error]     expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2
[error]     statement →  ● expressions_or_clauses statement$subexpression$1
[error]     main$ebnf$1 → main$ebnf$1 ● statement
[error]     main →  ● main$ebnf$1
[error] A DOT token based on:
[error]     property_access → simple_expression _ ● %DOT _ property_access$subexpression$1
[error]     simple_expression_without_asterisk$subexpression$1 →  ● property_access
[error]     simple_expression_without_asterisk →  ● simple_expression_without_asterisk$subexpression$1
[error]     simple_expression$subexpression$1 →  ● simple_expression_without_asterisk
[error]     simple_expression →  ● simple_expression$subexpression$1
[error]     between_predicate → %BETWEEN _ ● simple_expression _ %AND _ simple_expression
[error]     expression$subexpression$1 →  ● between_predicate
[error]     expression →  ● expression$subexpression$1
[error]     other_clause$ebnf$1 → other_clause$ebnf$1 ● expression
[error]     other_clause → %RESERVED_COMMAND ● other_clause$ebnf$1
[error]     clause$subexpression$1 →  ● other_clause
[error]     clause →  ● clause$subexpression$1
[error]     expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause
[error]     expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2
[error]     statement →  ● expressions_or_clauses statement$subexpression$1
[error]     main$ebnf$1 → main$ebnf$1 ● statement
[error]     main →  ● main$ebnf$1
[error] A LINE_COMMENT token based on:
[error]     comment →  ● %LINE_COMMENT
[error]     _$ebnf$1 → _$ebnf$1 ● comment
[error]     _ →  ● _$ebnf$1
[error]     property_access → simple_expression ● _ %DOT _ property_access$subexpression$1
[error]     simple_expression_without_asterisk$subexpression$1 →  ● property_access
[error]     simple_expression_without_asterisk →  ● simple_expression_without_asterisk$subexpression$1
[error]     simple_expression$subexpression$1 →  ● simple_expression_without_asterisk
[error]     simple_expression →  ● simple_expression$subexpression$1
[error]     between_predicate → %BETWEEN _ ● simple_expression _ %AND _ simple_expression
[error]     expression$subexpression$1 →  ● between_predicate
[error]     expression →  ● expression$subexpression$1
[error]     other_clause$ebnf$1 → other_clause$ebnf$1 ● expression
[error]     other_clause → %RESERVED_COMMAND ● other_clause$ebnf$1
[error]     clause$subexpression$1 →  ● other_clause
[error]     clause →  ● clause$subexpression$1
[error]     expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause
[error]     expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2
[error]     statement →  ● expressions_or_clauses statement$subexpression$1
[error]     main$ebnf$1 → main$ebnf$1 ● statement
[error]     main →  ● main$ebnf$1
[error] A BLOCK_COMMENT token based on:
[error]     comment →  ● %BLOCK_COMMENT
[error]     _$ebnf$1 → _$ebnf$1 ● comment
[error]     _ →  ● _$ebnf$1
[error]     property_access → simple_expression ● _ %DOT _ property_access$subexpression$1
[error]     simple_expression_without_asterisk$subexpression$1 →  ● property_access
[error]     simple_expression_without_asterisk →  ● simple_expression_without_asterisk$subexpression$1
[error]     simple_expression$subexpression$1 →  ● simple_expression_without_asterisk
[error]     simple_expression →  ● simple_expression$subexpression$1
[error]     between_predicate → %BETWEEN _ ● simple_expression _ %AND _ simple_expression
[error]     expression$subexpression$1 →  ● between_predicate
[error]     expression →  ● expression$subexpression$1
[error]     other_clause$ebnf$1 → other_clause$ebnf$1 ● expression
[error]     other_clause → %RESERVED_COMMAND ● other_clause$ebnf$1
[error]     clause$subexpression$1 →  ● other_clause
[error]     clause →  ● clause$subexpression$1
[error]     expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause
[error]     expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2
[error]     statement →  ● expressions_or_clauses statement$subexpression$1
[error]     main$ebnf$1 → main$ebnf$1 ● statement
[error]     main →  ● main$ebnf$1
[error]
[error]     at Parser.feed (/opt/homebrew/lib/node_modules/prettier-plugin-sql/node_modules/nearley/lib/nearley.js:343:27)
[error]     at Object.parse (/opt/homebrew/lib/node_modules/prettier-plugin-sql/node_modules/sql-formatter/lib/parser/createParser.js:48:33)
[error]     at SqlFormatter.parse (/opt/homebrew/lib/node_modules/prettier-plugin-sql/node_modules/sql-formatter/lib/formatter/Formatter.js:93:70)
[error]     at SqlFormatter.format (/opt/homebrew/lib/node_modules/prettier-plugin-sql/node_modules/sql-formatter/lib/formatter/Formatter.js:85:22)
[error]     at Object.format (/opt/homebrew/lib/node_modules/prettier-plugin-sql/node_modules/sql-formatter/lib/sqlFormatter.js:127:36)
[error]     at Object.print (/opt/homebrew/lib/node_modules/prettier-plugin-sql/lib/index.cjs:183:66)
[error]     at callPluginPrintFunction (/opt/homebrew/lib/node_modules/prettier/index.js:8420:26)
[error]     at mainPrintInternal (/opt/homebrew/lib/node_modules/prettier/index.js:8369:22)
[error]     at mainPrint (/opt/homebrew/lib/node_modules/prettier/index.js:8356:18)
[error]     at printAstToDoc (/opt/homebrew/lib/node_modules/prettier/index.js:8348:18)
 ✘ choongjaelee@Timui-MacBookPro  ~/Desktop/Codes/bq  npx sql-formatter SELECT *
FROM a
WHERE d BETWEEN DATE_TRUNC(PARSE_DATE("%Y%m%d", d1), MONTH) AND PARSE
 ✘ choongjaelee@Timui-MacBookPro  ~/Desktop/Codes/bq  npx sql-formatter hello.sql
/opt/homebrew/lib/node_modules/sql-formatter/dist/sql-formatter.min.cjs:1
!function(E,T){"object"==typeof exports&&"object"==typeof module?module.exports=T():"function"==typeof define&&define.amd?define([],T):"object"==typeof exports?exports.sqlFormatter=T():E.sqlFormatter=T()}(this,(()=>(()=>{var E=

... (omitted last part)
```

**Usage**

- How are you calling / using the library?
terminal / intellij both
- What SQL language(s) does this apply to?
bigquery
- Which SQL Formatter version are you using?
sql-formatter@12.0.1

**Comment by tim-watcha** [comment]
it turns out that I need to give an option "-l bigquery"
