### ISSUE TITLE
[FORMATTING] Issue Title Here

### ISSUE THREAD

**Issue by lrx1234** [sql-formatter-org/sql-formatter#529]
**Input data**

Which SQL and options did you provide as input?

```sql
-- SELECT OWNER "tabSchema", TABLE_NAME "tabName" FROM SYS.DBA_TAB_COLUMNS WHERE OWNER NOT IN (?, ?, ?) AND DATA_TYPE = ? AND DATA_LENGTH > ? GROUP BY OWNER, TABLE_NAME
```

**Expected Output**

```sql
-- SELECT
  OWNER "tabSchema",
  TABLE_NAME "tabName"
FROM
  SYS.DBA_TAB_COLUMNS
WHERE
  OWNER NOT IN (?, ?, ?)
  AND DATA_TYPE = ?
  AND DATA_LENGTH > ?
GROUP BY
  OWNER,
  TABLE_NAME
```

**Actual Output**

```sql
An error is hanppened when formatting
Error: Parse error: Unexpected "?, ?, ?)"
    at E.value (chunk-6ebc1296.b1ab3a22.js:1:141716)
    at R.value (chunk-6ebc1296.b1ab3a22.js:1:113485)
    at v (chunk-6ebc1296.b1ab3a22.js:1:161393)
    at o.formatText (chunk-commons.621df829.js:1:15959)
    at o.n [as formatText] (chunk-libs.f0c281b1.js:67:1465)
    at o.formatSql (chunk-17d5c3d0.4e0ad746.js:1:14800)
    at n (chunk-libs.f0c281b1.js:67:1453)
    at o.t (chunk-libs.f0c281b1.js:67:12671)
    at e.$emit (chunk-libs.f0c281b1.js:67:16478)
    at o.handleClick (chunk-elementUI.f8bf9c40.js:1:170864)
```

**Usage**

- How are you calling / using the library?
- ---formatter(sqltext, { language: 'plsql' })
- What SQL language(s) does this apply to?
- ---plsql
- Which SQL Formatter version are you using?
- ---7.0.2

**Comment by nene** [comment]
Use the [paramTypes](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md) config option to configure what sort of parameter syntax you need. For example:

```js
format(sql, {
  paramTypes: { positional: true }
});
```
