### ISSUE TITLE
[FORMATTING] SQL that contains "\n" throws exception

### ISSUE THREAD

**Issue by maxkremer** [sql-formatter-org/sql-formatter#625]
**Input data**

Any SQL that has \n

```sql
select supplier_name,city from
where  supplier_id>500 \n
order by supplier_name asc,city desc;
```

**Expected Output**

Should render normally, ignoring the carriage return or respecting it depending on the parser.

**Actual Output**

```
Error: Parse error: Unexpected "\n
order b" at line 2 column 24
    at iR.createParseError (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:191542)
    at iR.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:191328)
    at YR.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:192718)
    at JR.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:225154)
    at JR.reset (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:197686)
    at T.I.feed (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:4085)
    at Object.parse (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:225309)
    at PA.parse (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:225504)
    at PA.format (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:225017)
    at rA (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:229805)
```

You can reproduce above here: https://sql-formatter-org.github.io/sql-formatter/

**Comment by maxkremer** [comment]
sometimes you are generating SQL string on the backend with newline characters. Usually this is for readability in the log, helpful for big SQL queries with lots of wrapping.

If you want to pass these queries to another source for rendering/formatting the \n will be present.

**Comment by nene** [comment]
This `\n` is not part of SQL syntax. I don't know of any SQL dialect that supports it. Therefore the formatter also does not support it. This is as designed. Not a bug.

Simply replace `\n` with actual newline character before passing the SQL to the formatter.
