### ISSUE TITLE
[FORMATTING] Issue Title Here

### ISSUE THREAD

**Issue by GolderBrother** [sql-formatter-org/sql-formatter#630]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT ip_name,
    max(cate_name) as cate_name,
    max(title) as title,
    count(cid) as n_cid
FROM(
    SELECT 
        CONCAT(ip_name, '_', SPLIT(cate_name_list, '#')[0]) AS ip_name, 
        SPLIT(cate_name_list, '#')[0] AS cate_name,
        title,
        cid
    FROM ${INPUT_TABLE1}
)GROUP BY ip_name
```

**Expected Output**

```sql
SELECT
  ip_name,
  max(cate_name) as cate_name,
  max(title) as title,
  count(cid) as n_cid
FROM
(
    SELECT
      CONCAT(ip_name, '_', SPLIT(cate_name_list, '#') [0]) AS ip_name,
      SPLIT(cate_name_list, '#') [0] AS cate_name,
      title,
      cid
    FROM
      $ { INPUT_TABLE1 }
  )
GROUP BY
  ip_name
```

**Actual Output**

```
runtime-core.esm-bundler.js:218 Uncaught Error: Parse error: Unexpected "[0]) AS ip" at line 7 column 56
    at TokenizerEngine.createParseError (TokenizerEngine.ts:61:12)
    at TokenizerEngine.tokenize (TokenizerEngine.ts:49:22)
    at Tokenizer.tokenize (Tokenizer.ts:26:47)
    at LexerAdapter.tokenize (createParser.ts:23:37)
    at LexerAdapter.reset (LexerAdapter.ts:18:24)
    at Parser.feed (nearley.js:281:15)
    at Object.parse (createParser.ts:33:34)
    at Formatter.parse (Formatter.ts:41:49)
    at Formatter.format (Formatter.ts:33:22)
    at formatDialect (sqlFormatter.ts:94:57)
    at format (sqlFormatter.ts:67:10)
    at formatSql (formatSql.ts:16:15)
    at formatterCode (editor.vue:106:21)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:721:9)
    at runtime-core.esm-bundler.js:7348:53
    at Proxy.handleClick (index.js:58:7)
    at createElementBlock.onClick._cache.<computed>._cache.<computed> (index.js:91:78)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:369:13)
```

**Usage**
- How are you calling / using the library?
```js
import { format, FormatOptions } from 'sql-formatter'; // sql格式化插件

export function formatSql(sqlText: string, options: FormatOptions = {
  language: 'sql'
}) {
  const list: string[] = []
  const slotValue = 'onelight_today_wonderful_dayppppppppppp_PPPPPP_ppppp_ggggg'

  // 这个正则需要跟后端对齐，保留规则统一！！！
  const formatValue = sqlText.replace(/\$\{.*?\}/g, v => {
    list.push(v);
    return slotValue
  });

  const val = format(formatValue, options)
  let index = 0;
  // eslint-disable-next-line no-plusplus
  return val.replace(new RegExp(slotValue, 'g'), (v) => list[index++])
}
formatSql(xxx);
```
- What SQL language(s) does this apply to?
```js
options = {
  language: 'sql'
}
```
- Which SQL Formatter version are you using?
`sql-formatter@12.2.4`

**Comment by nene** [comment]
Please read the FAQ: https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-

**Comment by GolderBrother** [comment]
> Please read the FAQ: https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-

ok，This looks good, I'll try it

**Comment by nene** [comment]
The `sql` language only supports the most common SQL syntax that's shared by most SQL dialects. Like it will recognize `"foo"` as quoted identifier, but it will have no idea what the meaning of `[foo]` is.

The `transactsql` language targets the SQL dialect used by Microsoft SQL Server. Like it will recognize `[foo]` is a quoted identifier.
