### ISSUE TITLE
[FORMATTING] format error of symbol ` 

### ISSUE THREAD

**Issue by liaorg** [sql-formatter-org/sql-formatter#650]
**Input data**

Which SQL and options did you provide as input?

```sql
show columns from `test`.`dbaudit_index`
```

**Expected Output**

```sql
show columns
from
  `test`.`dbaudit_index`
```

**Actual Output**

```sql
Error: Parse error: Unexpected "`test`.`db" at line 1 column 19
    at GR.createParseError ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.
min.cjs:1:174261?[90m)?[39m
    at GR.tokenize ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:
1:174047?[90m)?[39m
    at FR.tokenize ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:
1:175437?[90m)?[39m
    at $R.tokenize ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:
1:207873?[90m)?[39m
    at $R.reset ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:1:1
80405?[90m)?[39m
    at T.I.feed ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:1:4
085?[90m)?[39m
    at Object.parse ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs
:1:208028?[90m)?[39m
    at PA.parse ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:1:2
08223?[90m)?[39m
    at PA.format ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:1:
207736?[90m)?[39m
    at nA ?[90m(C:\work\hello-arco-pro\?[39mnode_modules\?[4msql-formatter?[24m\dist\sql-formatter.min.cjs:1:212524?
[90m)?[39m

Node.js v18.14.1
```

**Usage**

- How are you calling / using the library? nodejs
- What SQL language(s) does this apply to? transactsql
- Which SQL Formatter version are you using? 13.0.0

**Comment by nene** [comment]
This doesn't look like valid Transact-SQL.

Does Transact-SQL allow quoting identifiers with backticks? If so, could you please refer to the relevant documentation.
